---
collections:
  - name: stackhpc.cephadm
    version: 1.13.1
  # NOTE: Pinning pulp.squeezer to 0.0.13 because 0.0.14+ depends on the
  # pulp_glue Python library being installed.
  - name: pulp.squeezer
    version: 0.0.13
  - name: stackhpc.pulp
    version: 0.4.1
roles:
  - src: stackhpc.vxlan
  - name: wazuh-ansible
    src: https://github.com/stackhpc/wazuh-ansible
    version: stackhpc
