---
- name: Pre-checks
  gather_facts: false
  hosts: localhost
  tags:
    - prechecks
  tasks:
    - block:
        - name: Fail if using old path for Wazuh certificates
          fail:
            msg: >-
              The path used for Wazuh SSL certificates was changed in a previous release. The certificates
              were found in the wrong location. Please move them from {{ playbook_dir }}/wazuh/certificates
              to {{ kayobe_env_config_path }}/wazuh/certificates.
          when:
            - playbook_dir ~ '/wazuh/certificates' is exists

        - name: Fail if using old path for custom certificates
          fail:
            msg: >-
              Wazuh custom SSL certificates have been merged with regular certificates. The certificates
              were found in the wrong location. Please move them from {{ playbook_dir }}/wazuh/custom_certificates
              to {{ kayobe_env_config_path }}/wazuh/certificates/certs.
          when:
            - playbook_dir ~ '/wazuh/custom_certificates' is exists

        - name: Check that removed variable, local_custom_certs_path, is not set
          assert:
            that: local_custom_certs_path is not defined
            fail_msg: "The variable, `local_custom_certs_path`, is no longer used. Please remove this variable."
      when:
        - groups["wazuh-manager"] | length > 0 or True

# Certificates generation
- hosts: localhost
  roles:
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-indexer"
      perform_installation: false
  become: no
  tags:
    - generate-certs
# Single node
- hosts: wazuh-manager
  become: yes
  become_user: root
  roles:
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-indexer"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-wazuh-manager"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/ansible-filebeat-oss"
    - role: "{{ playbook_dir }}/roles/wazuh-ansible/wazuh-ansible/roles/wazuh/wazuh-dashboard"
  post_tasks:
    - name: Set http/s_proxy vars in ossec-init.conf for vulnerability detector
      blockinfile:
        path: "/var/ossec/etc/ossec.conf"
        state: present
        owner: root
        group: ossec
        block: |
          HTTPS_PROXY={{ http_proxy_url }}
          HTTP_PROXY={{ http_proxy_url }}
        backup: yes
      when: http_proxy_url is defined
      notify:
        - Restart wazuh

    - name: Perform health check against filebeat
      command: filebeat test output
      changed_when: false
      become: true
      retries: 2

  handlers:
    - name: Restart wazuh
      service:
        name: wazuh-manager
        state: restarted
